const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
let API=localStorage.getItem("minirag_api")||"", selectedFile=null, lastResponse=null, lastSearch=null;
$("#apiUrl").value=API;
function toast(m){let t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2600)}
async function req(path,opt={}){let r=await fetch(API+path,opt);let txt=await r.text();let data;try{data=JSON.parse(txt)}catch{data={raw:txt}}if(!r.ok)throw new Error(data.detail||data.signal||data.raw||("HTTP "+r.status));return data}
async function health(){try{await fetch(API+"/docs",{mode:"cors"});$("#apiDot").style.background="#22c55e";$("#apiState").textContent="Connected"}catch{$("#apiDot").style.background="#ef4444";$("#apiState").textContent="Offline"}}
health();
$$(".nav").forEach(b=>b.onclick=()=>{$$(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");$$(".view").forEach(v=>v.classList.remove("active-view"));$("#"+b.dataset.view).classList.add("active-view")});
$("#settingsBtn").onclick=()=>$("#settingsModal").classList.remove("hidden");$("#closeSettings").onclick=()=>$("#settingsModal").classList.add("hidden");
$("#saveSettings").onclick=()=>{API=$("#apiUrl").value.replace(/\/$/,"");localStorage.setItem("minirag_api",API);$("#settingsModal").classList.add("hidden");health();toast("Backend connection saved")};
$("#uploadTop").onclick=()=>$("#fileInput").click();$("#browseBtn").onclick=()=>$("#fileInput").click();
function setFile(f){selectedFile=f;$("#fileName").textContent=f.name;$("#fileSize").textContent=(f.size/1024/1024).toFixed(2)+" MB";$("#fileCard").classList.remove("hidden");$("#runPipeline").disabled=false}
$("#fileInput").onchange=e=>e.target.files[0]&&setFile(e.target.files[0]);
["dragenter","dragover"].forEach(ev=>$("#dropzone").addEventListener(ev,e=>{e.preventDefault();$("#dropzone").classList.add("drag")}));
["dragleave","drop"].forEach(ev=>$("#dropzone").addEventListener(ev,e=>{e.preventDefault();$("#dropzone").classList.remove("drag")}));
$("#dropzone").addEventListener("drop",e=>e.dataTransfer.files[0]&&setFile(e.dataTransfer.files[0]));
function pid(){return Number($("#projectId").value||1)}
$("#projectId").oninput=()=>{$("#projectMetric").textContent="#"+pid();refreshInfo()};
$("#limit").onchange=()=>$("#topKMetric").textContent="Top "+$("#limit").value;
$("#runPipeline").onclick=async()=>{if(!selectedFile)return;let btn=$("#runPipeline");btn.disabled=true;btn.innerHTML="Building pipeline…";$("#pipelineMetric").textContent="Running";$("#pipelineSub").textContent="Upload → chunk → embed";
try{let fd=new FormData();fd.append("file",selectedFile);let up=await req(`/api/v1/data/upload/${pid()}`,{method:"POST",body:fd});let body={file_id:up.file_id,chunk_size:Number($("#chunkSize").value),chunk_overlap:Number($("#overlap").value),do_reset:$("#reset").checked?1:0};let job=await req(`/api/v1/data/process_and_push/${pid()}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});$("#taskId").textContent=job.task_id;$("#taskBox").classList.remove("hidden");$("#pipelineMetric").textContent="Queued";$("#pipelineSub").textContent="Celery task received";toast("Document uploaded. Celery pipeline started.");setTimeout(refreshInfo,2500)}catch(e){$("#pipelineMetric").textContent="Error";$("#pipelineSub").textContent=e.message;toast(e.message)}finally{btn.disabled=false;btn.innerHTML="<span>▶</span> Upload & build knowledge index"}};
async function refreshInfo(){try{let d=await req(`/api/nlp/info/${pid()}`);let c=d.collection_info||{};let count=c.rows_count??c.count??c.points_count??"—";$("#vectorMetric").textContent=count;$("#pipelineMetric").textContent=count!=="—"?"Indexed":"Ready";$("#pipelineSub").textContent=count!=="—"?"Knowledge base available":"Waiting for input"}catch(e){$("#vectorMetric").textContent="—"}}
$("#refreshInfo").onclick=refreshInfo;refreshInfo();
$$(".suggestions button").forEach(b=>b.onclick=()=>{$("#question").value=b.textContent;ask()});
$("#askBtn").onclick=ask;$("#question").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask()}});
function bubble(role,text){let w=$("#messages");let welcome=w.querySelector(".welcome");if(welcome)welcome.remove();let d=document.createElement("div");d.className="bubble "+role;d.innerHTML=`<span class="role">${role==="user"?"YOU":"MINIRAG"}</span>${escapeHtml(text)}`;w.appendChild(d);w.scrollTop=w.scrollHeight;return d}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function ask(){let q=$("#question").value.trim();if(!q)return;$("#question").value="";bubble("user",q);let loading=bubble("ai","Retrieving context and generating an answer…");$("#askBtn").disabled=true;
try{let body={text:q,limit:Number($("#limit").value)};try{lastSearch=await req(`/api/nlp/index/search/${pid()}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)})}catch{lastSearch=null}lastResponse=await req(`/api/nlp/index/answer/${pid()}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});loading.innerHTML=`<span class="role">MINIRAG</span>${escapeHtml(lastResponse.answer||"No answer returned.")}`;renderTrace("sources")}catch(e){loading.innerHTML=`<span class="role">ERROR</span>${escapeHtml(e.message)}`;toast(e.message)}finally{$("#askBtn").disabled=false}}
function renderTrace(type){let el=$("#traceContent");el.className="trace-data";if(type==="sources")el.textContent=lastSearch?JSON.stringify(lastSearch.results||lastSearch,null,2):"Search trace is unavailable for this request.";if(type==="prompt")el.textContent=lastResponse?.full_prompt||"No prompt returned yet.";if(type==="raw")el.textContent=lastResponse?JSON.stringify(lastResponse,null,2):"No response yet."}
$$(".trace-tabs button").forEach(b=>b.onclick=()=>{$$(".trace-tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderTrace(b.dataset.trace)});
$("#clearChat").onclick=()=>{lastResponse=lastSearch=null;$("#messages").innerHTML=`<div class="welcome"><div class="orb">✦</div><h3>Your knowledge is ready to talk.</h3><p>Ask a question about your indexed documents. MiniRAG will retrieve the most relevant chunks and generate a grounded answer.</p><div class="suggestions"><button>Summarize the key ideas</button><button>What are the main recommendations?</button><button>Explain the most important concept</button></div></div>`;$$(".suggestions button").forEach(b=>b.onclick=()=>{$("#question").value=b.textContent;ask()});$("#traceContent").className="trace-empty";$("#traceContent").innerHTML="<span>⌕</span><div><b>No retrieval yet</b><p>Ask a question to inspect what the model retrieved and used.</p></div>"};
