services:
  mongodb:
    image: mongo:7-jammy
    container_name: Mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: