"""add task args to celery task execution

Revision ID: b4020cf7d0d2
Revises: 2fc364f07804
Create Date: 2026-08-31 15:51:07.912790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4020cf7d0d2'
down_revision: Union[str, None] = '2fc364f07804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Celery_task_execution', sa.Column('task_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Celery_task_execution', 'task_args')
    # ### end Alembic commands ###
