"""first version

Revision ID: c558e7978e80
Revises: 
Create Date: 2026-08-11 19:35:08.065758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c558e7978e80'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Projects',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('project_uuid')
    )
    op.create_table('Assets',
    sa.Column('Asset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Asset_uuid', sa.UUID(), nullable=False),
    sa.Column('Asset_name', sa.String(), nullable=False),
    sa.Column('Asset_type', sa.String(), nullable=False),
    sa.Column('Asset_size', sa.Integer(), nullable=False),
    sa.Column('Asset_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('Asset_project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['Asset_project_id'], ['Projects.project_id'], ),
    sa.PrimaryKeyConstraint('Asset_id'),
    sa.UniqueConstraint('Asset_uuid')
    )
    op.create_index('ix_Asset_project_id', 'Assets', ['Asset_project_id'], unique=False)
    op.create_table('Chunks',
    sa.Column('Chunks_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Chunks_uuid', sa.UUID(), nullable=False),
    sa.Column('Chunk_text', sa.String(), nullable=False),
    sa.Column('Chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('Chunk_project_id', sa.Integer(), nullable=False),
    sa.Column('Chunk_asset_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['Chunk_asset_id'], ['Assets.Asset_id'], ),
    sa.ForeignKeyConstraint(['Chunk_project_id'], ['Projects.project_id'], ),
    sa.PrimaryKeyConstraint('Chunks_id'),
    sa.UniqueConstraint('Chunks_uuid')
    )
    op.create_index('ix_Chunk_project_id', 'Chunks', ['Chunk_project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Chunk_project_id', table_name='Chunks')
    op.drop_table('Chunks')
    op.drop_index('ix_Asset_project_id', table_name='Assets')
    op.drop_table('Assets')
    op.drop_table('Projects')
    # ### end Alembic commands ###
